# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: public_rescue 0.6.0 ruby lib

Gem::Specification.new do |s|
  s.name = "public_rescue"
  s.version = "0.6.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Cyril Picard"]
  s.date = "2016-05-30"
  s.description = "PublicRescue is a gem for rails application who want to display dynamic error pages. It creates a new Rack middleware which replaces ActionDispatch::ShowExceptions and overwrites the rescue_action_in_public method."
  s.email = "Cyril@picard.ch"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "app/controllers/public_rescue/public_errors_controller.rb",
    "app/views/public_rescue/public_errors/internal_server_error.html.erb",
    "app/views/public_rescue/public_errors/not_found.html.erb",
    "app/views/public_rescue/public_errors/unprocessable_entity.html.erb",
    "lib/generators/public_rescue/public_rescue_generator.rb",
    "lib/generators/public_rescue/views_generator.rb",
    "lib/generators/template/controller.rb",
    "lib/public_rescue.rb",
    "lib/public_rescue/public_exceptions.rb",
    "lib/public_rescue/public_exceptions3.rb",
    "lib/public_rescue/rails.rb",
    "lib/public_rescue/show_exceptions.rb",
    "public_rescue.gemspec",
    "test/helper.rb",
    "test/test_public_rescue.rb"
  ]
  s.homepage = "http://github.com/cyrilpic/public_rescue"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.5.1"
  s.summary = "Rails gem for displaying dynamic error pages."

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rails>, [">= 3.0"])
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.11.2"])
      s.add_development_dependency(%q<jeweler>, ["~> 2.1.0"])
      s.add_development_dependency(%q<simplecov>, [">= 0"])
    else
      s.add_dependency(%q<rails>, [">= 3.0"])
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<bundler>, ["~> 1.11.2"])
      s.add_dependency(%q<jeweler>, ["~> 2.1.0"])
      s.add_dependency(%q<simplecov>, [">= 0"])
    end
  else
    s.add_dependency(%q<rails>, [">= 3.0"])
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<bundler>, ["~> 1.11.2"])
    s.add_dependency(%q<jeweler>, ["~> 2.1.0"])
    s.add_dependency(%q<simplecov>, [">= 0"])
  end
end

